version: '3'

services:
    # ingest - listening on port 8084
    lightspeed-ingest:     
        restart: on-failure
        build: ingest/
        ports:
            - "8084:8084"
    
    # react - serves on port 80, needs the wsUrl which is webrtc ip:8080
    lightspeed-react:    
        restart: on-failure
        build: react/
        ports:
            - "8080:80"

    # webrtc, defaults to localhost:8080. 
    lightspeed-webrtc:     
        restart: on-failure
        build: webrtc/
        ports:
            - "8888:8080"