version: '3'

services:
  lightspeed-ingest:     
    restart: on-failure
    build: 
      context: ../Lightspeed-ingest 
      dockerfile: Dockerfile
    image: lightspeed-ingest
    env_file: '.env'
    ports:
      - "${INGEST_PORT}:8084"
  
  lightspeed-react:    
    restart: on-failure
    image: lightspeed-react
    build:
      context: ../Lightspeed-react
      dockerfile: Dockerfile
    env_file: '.env'
    ports:
      - "${WEB_PORT}:80"

  lightspeed-webrtc:     
    restart: on-failure
    build: 
      context: ../Lightspeed-webrtc
      dockerfile: Dockerfile
    image: lightspeed-webrtc
    env_file: '.env'
    command: ["lightspeed-webrtc", "--addr=0.0.0.0", "--ip=${WEBSOCKET_HOST}", "--ports=20000-20500", "run"]
    ports:
      - ${WEBSOCKET_PORT}:8080 # WebRTC
      - 65535:65535/udp # RTP
      - 20000-20500:20000-20500 # WebRTC PeerConnection
      - 20000-20500:20000-20500/udp # WebRTC PeerConnection UDP