on: [push, pull_request]

name: Ingest Lint 

jobs:
  lint:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Add rustfmt and clippy
        run: rustup component add clippy
        run: rustup component add rustfmt
      - name: Check
        uses: actions-rs/cargo@v1
        working-directory: ./lightspeed-ingest
        with:
          command: check
      - name: Fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
        working-directory: ./lightspeed-ingest
      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
