on: [push, pull_request]

name: Ingest Lint 

jobs:
  lint:
    name: CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./lightspeed-ingest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Add clippy 
        run: rustup component add clippy
      - name: Add rustfmt
        run: rustup component add rustfmt
      - name: Check
        uses: actions-rs/cargo@v1
        with:
          args: --manifest-path ./lightspeed-ingest/Cargo.toml
          command: check
      - name: Fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all --manifest-path ./lightspeed-ingest/Cargo.toml  -- --check
      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path ./lightspeed-ingest/Cargo.toml -- -D warnings
